parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

define_aliases()
{
	source_file ~/.bash_aliases


	# apt-get aliases
	alias supdate='sudo apt-get update'
	alias sinstall='sudo apt-get install'
	alias supgrade='sudo apt-get upgrade'

	# git aliases
	alias gits='git status'
	alias gita='git add -A . && git status'
	alias gitc='git commit -m'
	alias gitp='git pull'

	# ROS
	alias cws='cd ~/catkin_ws'
	alias catb='(cd ~/catkin_ws && catkin build)'
	alias catc='(cd ~/catkin_ws && catkin clean -y)'
	alias qcws='cd ~/qnx_catkin_ws'
	alias qcatb='(cd ~/qnx_catkin_ws && qnxros build)'
	alias qcatc='(cd ~/qnx_catkin_ws && qnxros clean)'

	# Other
	alias sbrc='source ~/.bashrc'
	alias clr='clear'
}

application_specific()
{
	# ROS
	#source_file /opt/ros/indigo/setup.bash
	source_file /opt/ros/kinetic/setup.bash
	source_file ~/catkin_ws/devel/setup.bash
	export QNXROS_WS="$HOME/qnx_catkin_ws"
	source_file ~/Documents/wavelab/renesas-demo/scripts/qnx/qnxros.bash

	# anm_sim
	source ~/anm_sim/vrep_test_suite/scripts/test_suite_lib.bash

	# V-REP
	export VREP_ROOT=$HOME/opt/vrep/V-REP_PRO_EDU_V3_4_0_Linux


	# pip packages
	PATH=$PATH:~/.local/bin

	export PATH
}

source_file()
{
	if [ -f "$1" ]; then
		source "$1"
	fi
}

define_aliases
application_specific
